### ISSUE TITLE
OSError: [WinError 121] When i use await miner.get_config()

### ISSUE THREAD

**Issue by Awote** [UpstreamData/pyasic#100]
**Describe the bug**
When i want to get miner's config by ```miner.get_config()``` i get OSError: [WinError 121]

**To Reproduce**
1. get miner by ```await pyasic.get_miner(ip)```
2. try to get miner's config by await miner.get_config()
3. get error with OSError: [WinError 121]
.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - VPN NetExtender

**Miner Information (If applicable):**
 - Manufacturer: [IDK]
 - Type: [s19J Pro]
 - Firmware Type: [BraiinsOS]
 - Firmware Version: 2023-04-20-0-0ce150e9-23.03-plus

**Comment by b-rowan** [comment]
You need to update your miner to the latest version to use the latest version of pyasic, however im almost certain you dont want to do that.

Braiins made a bunch of changes to the API, and now pyasic is using gRPC by default on all new generation BOS+ miners, but I do not have support for send config until they fix some (pretty egregious) issues with their gRPC API.  Its not possible to keep using bosminer.toml on new versions anyway, so confiiguration on newer S19s will not work past `set_power_limit`.  I reccommend you keep using the version of miner you have, and pin pyasic to `pyasic==0.46.0`.
