### ISSUE TITLE
I want to know what pool a miner is currently active on

### ISSUE THREAD

**Issue by cryptographicturk** [UpstreamData/pyasic#135]
In the current MinerData, I can see what the pool configuration is, but if some of those pools are offline, there is no indication of that. Ideally I would like to know the status of every pool in the configuration, but at a minimum, I would like to know which pools are currently active.

**Comment by b-rowan** [comment]
This is actually currently WIP via the Summer of Bitcoin project.

https://www.summerofbitcoin.org/project-ideas-details/pyasic/r/recjb9HM1jM0WO1wv
