### ISSUE TITLE
I want to know the expected fans of a miner.

### ISSUE THREAD

**Issue by martyfay1** [UpstreamData/pyasic#136]
It would be nice to know the expected number of fans for a given miner. That way we can tell quickly if a miner is using less fans than expected. It would be ideal if this field could be added to MinerData.

**Comment by b-rowan** [comment]
This exists as `miner.expected_fans`, but not a bad idea to add to `MinerData` while I'm adding things to it

**Comment by martyfay1** [comment]
I didn't realize that it was in miner.expected_fans, thanks. If it is an easy change though having it in `MinerData` would still be nice.
