### ISSUE TITLE
wmt.pyasic.org source code or any other solution to unlock whatsminer asic privileged API

### ISSUE THREAD

**Issue by realrainer** [UpstreamData/pyasic#142]
Hello, 
Where i can find wmt.pyasic.org service source code or any other solution such as container or virtual machine to use whatsminer privileged api unlocker at local network? External service not useable due network security policy.

**Comment by UpstreamData** [comment]
Sadly, I can't release any sources or anything for this, as it contains some sensitive information and I would like to prevent it from being patched.
