### ISSUE TITLE
`RuntimeWarning: coroutine 'sleep' was never awaited` while calling `get_data`

### ISSUE THREAD

**Issue by martyfay1** [UpstreamData/pyasic#154]
I very frequently see the mentioned RuntimeWarning above while trying to `get_data` from miners. The line of code that is responsible for it is pyasic/miners/base.py", lineno 432 `api_command_task = asyncio.sleep(0)`. It would be nice to see this refactored to avoid the spam of RuntimeWarnings.

**Comment by b-rowan** [comment]
Should be improved if not fixed in 0.57.6, give that a test.

**Comment by martyfay1** [comment]
It's much better thanks!
