### ISSUE TITLE
Unable to modify power limit from HASS-Miner on S19 Pro+ Hydro Antminer BOS+

### ISSUE THREAD

**Issue by 928driver** [UpstreamData/pyasic#183]
**Is your feature request related to a problem? Please describe.**
I can add my miner in HA, start/stop the miner and read values from 3 hashboards. But not be able to change power limit. I see that my miner is not on the supported list yet with BOS+ installed, so that is probably the reason.

**Describe the solution you'd like**
Have support for S19 Pro+ Hydro Antminer BOS+ to be able to change power limit and see all hashboard values.

**Additional context**
If there is any information I can provide to help out, just let me know :)

**Comment by b-rowan** [comment]
Should be fixed in the next version, soon.

**Comment by b-rowan** [comment]
Fixed in 0.59.0.
