### ISSUE TITLE
RuntimeWarning: coroutine 'BOSerWebAPI.get_miner_stats' was never awaited

### ISSUE THREAD

**Issue by cryptographicturk** [UpstreamData/pyasic#201]
**Describe the bug**
When querying a lot of Braiins OS+ miners, we get an error repeated over again, but not 100% of the queries
RuntimeWarning: coroutine 'BOSerWebAPI.get_miner_stats' was never awaited

**To Reproduce**
Repeat this code in a loop going over a few hundred Braiins OS+ miners.
            pyasic_miner = await get_miner(ip)
            miner_data: MinerData = await pyasic_miner.get_data()

**Expected behavior**
No errors for not awaiting code

**Desktop (please complete the following information):**
Linux - Ubuntu 22.04

**Miner Information (If applicable):**
Bitmain Antminer S19J Pro, S19J Pro+ and S19 XP running Braiins OS+

**Comment by b-rowan** [comment]
Couple of missing await calls in the secondary calls made by the internal data gathering functions.  They don't get called unless the multicommand version of the call fails for some reason, so that's why it was only happening some of the time.
