### ISSUE TITLE
Antminer T21 running Braiins OS+ model Not Identified and missing data

### ISSUE THREAD

**Issue by cryptographicturk** [UpstreamData/pyasic#202]
Use pyasic to load data from a T21 running Braiins OS+, it does not detect the miner model, and it only includes data for 2 fans. Various other missing data.

**Comment by b-rowan** [comment]
Likely not in the supported list, can get it added.

**Comment by b-rowan** [comment]
Can confirm, not supported yet.  Base types are all there, just have to construct it and add it to the factory dict.

**Comment by b-rowan** [comment]
Done in `v0.60.5`
