### ISSUE TITLE
Avalon Nano 3 Integration

### ISSUE THREAD

**Issue by Tirael13** [UpstreamData/pyasic#207]
Please add support for the Avalon Nano 3 miner, thanks !

**Comment by Tirael13** [comment]
Actually, it worked out, I suppose it uses the same configs as the others from Avalon, thanks for this integration !

**Comment by Tirael13** [comment]
Actually, it worked out for almost all of the sensors, I suppose it uses the same configs as the others from Avalon, thanks for this integration !

![{2A047D69-63D0-4A8E-B71E-3B67BA5E68BE}](https://github.com/user-attachments/assets/204fd36c-ef2b-46cb-8947-df9d0b2386aa)

**Comment by b-rowan** [comment]
Nano3 was already supported actually, just not sure if it was in the docs.  I can update that.
