### ISSUE TITLE
Get nominal_hashrate data

### ISSUE THREAD

**Issue by Combinator78** [UpstreamData/pyasic#221]
In earlier versions of piasik, the **nominal_nashrate** field was returned. Is it possible to add this field in new versions?
This is convenient for specifying device models, for example S19k pro 110T, S19k pro 115T, S19k pro 120T and so on

**Comment by b-rowan** [comment]
Name was changed to `expected_hashrate`.  It's also not based on the sticker hashrate, but what the miner reports in its API as expected hashrate

**Comment by Combinator78** [comment]
Thank you

**Comment by Combinator78** [comment]
you can close the ticket
