### ISSUE TITLE
type issue: type of `env_temp` should be float

### ISSUE THREAD

**Issue by aquariuslt** [UpstreamData/pyasic#256]
## Issue Description

https://github.com/UpstreamData/pyasic/blob/2f2223a11208aa4a9ffee5ceb31c9bcfbfd90f7c/pyasic/data/__init__.py#L99

did not match description

https://github.com/UpstreamData/pyasic/blob/2f2223a11208aa4a9ffee5ceb31c9bcfbfd90f7c/pyasic/data/__init__.py#L55

when getting real data, the example value is `61.0` as float.

**Comment by b-rowan** [comment]
Out in version 0.66.1.
