### ISSUE TITLE
Thanks for this project guys. It is awesome. Will you add MAC address in miner's data ?

### ISSUE THREAD

**Issue by Awote** [UpstreamData/pyasic#28]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Awote** [comment]
thanks for help. i take mac
I have a question, will pyasic be able to detect the miner if the miner is connected via a switch -> router and pyasic directly to the router? I know the IP address of the miner.

**Comment by UpstreamData** [comment]
Yep, as long as the miner and the computer you are using pyasic on are connected to the same network, this will work perfectly fine.  Just run the above script with 
```python
asyncio.run(get_miner_mac(IP_ADDR_OF_MINER))
```

**Comment by UpstreamData** [comment]
For reference, if you need any more data from your miner, you can use the above script, but instead of `return data.mac` you can get any piece of data that is shown [here](https://pyasic.readthedocs.io/en/latest/data/miner_data/) by using the same format of `data.attribute`.

**Comment by UpstreamData** [comment]
Closing this for now, seems like it might have been resolved.

@Awote if you have any more questions feel free to re-open this or to create a new discussion in the "Discussions" tab.
