### ISSUE TITLE
CGMiner: send_ssh_command hides exceptions raised by _get_ssh_connection

### ISSUE THREAD

**Issue by Resolude** [UpstreamData/pyasic#36]
**Describe the bug**
pyasic.miners.backends.cgminer.CGMiner's send_ssh_command catches exceptions (asyncssh.Error, OSError) and returns None. This causes functions like stop_mining and resume mining, which lack an isinstance check, that call send_ssh_command to not have an exception raised to them. With the way stop_mining is written, the function will return True as long as no exception was raised, which makes it hard to detect SSH failures.

**To Reproduce**
1. Close or filter the SSH port on a cgminer
2. Try and call miner.stop_mining()

**Expected behavior**
stop_mining() should return false when there are SSH connection errors.

**Screenshots**

**Miner Information (If applicable):**
 - Manufacturer: Bitmain
 - Type: Z15
 - Firmware Type: Stock
 - Firmware Version: CGMiner 4.9.0

**Comment by UpstreamData** [comment]
Give it a test in v0.33.11?

**Comment by Resolude** [comment]
Looks good now. Thank you. stop_mining and resume_mining return False as expected.

**Comment by UpstreamData** [comment]
Awesome.  Thanks for the feedback, I'm relatively new to software development like this, so these things will likely happen quite a bit as I develop my software architecture abilities.  Let me know if you run into any more issues.
