### ISSUE TITLE
`is_mining` on Braiins OS+ with S19J Pro returns `True` even not mining

### ISSUE THREAD

**Issue by Schnitzel** [UpstreamData/pyasic#52]
**Describe the bug**
I got an S19J Pro with Braiins OS+, when i run `stop_mining()` the attribute `is_mining` always returns `True`, even though the miner actually stops mining.

**Expected behavior**
`is_mining` returns `False` when `stop_mining()` is sent

**Miner Information (If applicable):**
 - Manufacturer: Bitmain
 - Type: S19J Pro
 - Firmware Type: Braiins OS+
 - Firmware Version: `2023-03-05-0-8cbe158f-23.02-plus`

**Comment by UpstreamData** [comment]
This seems to be related to some type of miners on braiins OS stopping the tuner when the pause command is sent, and others seem to not report that the tuner is not running.  I'll see what I can do.

**Comment by UpstreamData** [comment]
Should be fixed in 0.36.5
