### ISSUE TITLE
remove print statements

### ISSUE THREAD

**Issue by Schnitzel** [UpstreamData/pyasic#53]
**Is your feature request related to a problem? Please describe.**
There are some print statements which fill the logs in tools like homeassistant when pyasic is used

**Describe the solution you'd like**
no print statements 

**Additional context**
Found this one: https://github.com/UpstreamData/pyasic/blob/e1500bb75c9d365d33b5606cb55a06ca7cd4ef18/pyasic/web/bosminer.py#L149C1-L150 
but there might also be others

**Comment by UpstreamData** [comment]
Removed those, just forgot some of those.  I'll work on your other issue and see what I can do there, then I'll release a version with the fixes.

**Comment by UpstreamData** [comment]
Done in 0.36.5
