### ISSUE TITLE
Is it possible to use same change password algorithm as whatsminer tools?

### ISSUE THREAD

**Issue by trycontrolmymind** [UpstreamData/pyasic#58]
**Is your feature request related to a problem? Please describe.**
To use commands on whatsminer you always have to use whatsminer tools to change default password

Is it possible to use the same protocol as they do with sending some TCP packages to port 8889?

**Comment by UpstreamData** [comment]
Unless someone knows the type of encoding and schema they use on 8889, it's not possible.  8889 is used by the Whatsminer tool, and they are using something called the "super-user" account, which I don't have the information to access.

If someone has this I would love to implement it, as it is much more powerful than even the privileged API, even supporting SSH unlock, but I consider this to be a very well guarded secret on the part of MicroBT.
