### ISSUE TITLE
expose highest chip temperature

### ISSUE THREAD

**Issue by Schnitzel** [UpstreamData/pyasic#68]
**Is your feature request related to a problem? Please describe.**
On the BraiinsOS UI there is a "Temperature (Chip)" which takes the highest chip temperature, pyasic only exposes the individual chip temperatures, making it a bit hard to easily get the highest chip temperature

**Describe the solution you'd like**
it would be great if pyasic returns the highest chip temperature

**Describe alternatives you've considered**
I could do this also in HomeAssistant but I feel it's easier in pyasic as the way that temperature is reported could be different per miner type

**Comment by UpstreamData** [comment]
I could do this as part of miner data, but it seems possibly redundant?

Would it be better to just use max + a list comp (```max([hb.chip_temp for hb in data.hashboards])```)?
