### ISSUE TITLE
Vnish miners don't return configs and pool info

### ISSUE THREAD

**Issue by Awote** [UpstreamData/pyasic#72]
Vnish miners when trying to get information via miner.api.pools or miner.get_config returns None.

**Comment by UpstreamData** [comment]
Good to know.  Working on fixing configs, as well as better Vnish support, so hopefully I can fix this soon.

**Comment by s0kil** [comment]
@Awote What is your Vnish version?

**Comment by Awote** [comment]
@s0kil  '1.2.0-rc4'

**Comment by s0kil** [comment]
@Awote I've tested with multiple machines we have running on 1.2.0-rc4, can't reproduce the issue you are having.

Make sure your `pyasic` version is up to date:
```bash
pip3 install pyasic --upgrade
```

**Comment by Awote** [comment]
i used version 0.45.0 before your last message @crc32 . Thenn i updated and tested.
```import asyncio
import pyasic

async def t(ip):
    miner = await pyasic.get_miner(ip)
    config = await miner.get_config()
    pool = await miner.api.pools()
    pass
asyncio.run(t("10.1.60.211"))

async def t1(ip):
    net = pyasic.MinerNetwork(ip)
    pyasic_miners = await net.scan_network_for_miners()
    pass

asyncio.run(t1("10.1.60.1-10.1.60.255"))```

first ffunnc return correct but second return empty list in Terminal i have issues:
[WARNING][11/28/23 10:14:52](root) - .: Unhandled ping exception: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
c:\Users\NeShdw\Desktop\1\venv\Lib\site-packages\pyasic\network\__init__.py:204 in ping_and_get_miner
[WARNING][11/28/23 10:14:52](root) - .: Unhandled ping exception: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
c:\Users\NeShdw\Desktop\1\venv\Lib\site-packages\pyasic\network\__init__.py:204 in ping_and_get_miner
[WARNING][11/28/23 10:14:52](root) - .: Unhandled ping exception: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
c:\Users\NeShdw\Desktop\1\venv\Lib\site-packages\pyasic\network\__init__.py:204 in ping_and_get_miner
[WARNING][11/28/23 10:14:52](root) - .: Unhandled ping exception: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
c:\Users\NeShdw\Desktop\1\venv\Lib\site-packages\pyasic\network\__init__.py:204 in ping_and_get_miner
[WARNING][11/28/23 10:14:52](root) - .: Unhandled ping exception: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
c:\Users\NeShdw\Desktop\1\venv\Lib\site-packages\pyasic\network\__init__.py:204 in ping_and_get_miner
[WARNING][11/28/23 10:14:52](root) - .: Unhandled ping exception: encoding with 'idna' codec failed (UnicodeError: label empty or too long)

**Comment by Awote** [comment]
Maybe i should use only 
```
get_miner()
```
on every ip rather than

```
scan_network_for_miners
```
?

**Comment by UpstreamData** [comment]
Try 0.41.0 with `await MinerNetwork.from_address("10.1.60.1-255").scan()`

**Comment by Awote** [comment]
if i use this ```await MinerNetwork.from_address("10.1.60.1-255").scan()``` i ll get not at all miners (80% of all miners). 
if i use ```scan_network_for_miner ``` in pyasic==0.45.0 , i ll get all miners

**Comment by Awote** [comment]
And some times i get error "POOLS" which maybe mean that ```pyasic``` can't get miner's pools

**Comment by UpstreamData** [comment]
> Some thing interesting. on first iteration pyasic find 30 miners (for example), on second iteration it find 50 miners which include some of first iteration miners and new miners. I really don't know why does it happen

This should be much more consistent as of `0.42.2`, but if youre still having issues on that version you can set the settings timeouts with `pyasic.settings.update(k, v)`.  Possible settings options are shown here - https://pyasic.readthedocs.io/en/latest/settings/settings/
