### ISSUE TITLE
add custom commands "cmd":"download_logs"

### ISSUE THREAD

**Issue by ph4n70m1984** [UpstreamData/pyasic#86]
could you write your command for example download logs

`
{
"token":"str", "cmd":"download_logs" 
}
`

**Comment by UpstreamData** [comment]
Yep, this can be done quite easily.  The only issue I believe is that download logs does something weird, not sure if I ever did implement it properly, but you can try it.

The way to do this is `miner.api.send_command("download_logs")`.

**Comment by UpstreamData** [comment]
Regarding the parameter, if you want to send an encoded command you can use `miner.api.send_privileged_command("download_logs")`, which parses the token and handles encoding for you with whatsminers.
