### ISSUE TITLE
miner.api.pools don't return miner's pools info

### ISSUE THREAD

**Issue by Awote** [UpstreamData/pyasic#99]
**Describe the bug**
When i want get miner's pools for check them status, i get empty value without Pool model. Why it could be ?

**To Reproduce**
1) miner = await pyasic.get_miner(ip)
2) pool = miner.api.pools()
3) Expected behavior

**Expected behavior**
 want to understand why on Bos miners sometimes i can't get pools info by miner.api.pools

**Miner Information (If applicable):**
- Type: S19j Pro (BOS)
- Firmware Type: BraiinsOS
- Firmware Version: 22.08.1

**Comment by b-rowan** [comment]
Not sure why this would be happening.  That being said, you should update that miner to the latest version of BraiinsOS+, as that version doesn't have gRPC which is what is used by most of pyasic to get data for new generation miners, as the new miners seem to have issues with doing things the old way.  From there, you should use `pyasic.get_config()`, as it will parse the config into a standard format for you (unless you're looking for submitted shares or something, in which case you can use `miner.web.grpc.get_pool_groups()`).
